const alumniProfiles = [
    { id: 1, name: 'John Doe', type: 'Alumni', title: 'CEO', company: 'TechCorp', image: '/assets/Images/large-pixabay-267885.jpg', expertise: 'Leadership & Strategy' },
    { id: 2, name: 'Jane Smith', type: 'Alumni', title: 'CTO', company: 'Innovatech', image: '/assets/Images/pexels-pavel-danilyuk-7942437.jpg', expertise: 'Technology & Innovation' },
    { id: 3, name: 'Alice Johnson', type: 'Alumni', title: 'CFO', company: 'FinCorp', image: '/assets/Images/pexels-andrea-piacquadio-3777553.jpg', expertise: 'Finance & Operations' },
    { id: 4, name: 'Michael Brown', type: 'Alumni', title: 'COO', company: 'BuildRight', image: '/assets/Images/pexels-fauxels-3182834.jpg', expertise: 'Operations & Management' },
    { id: 5, name: 'Emma Wilson', type: 'Alumni', title: 'CMO', company: 'MarketWave', image: '/assets/Images/pexels-cottonbro-studio-4063853.jpg', expertise: 'Marketing & Growth' },
    { id: 6, name: 'David Taylor', type: 'Alumni', title: 'CIO', company: 'DataSoft', image: '/assets/Images/pexels-tima-miroshnichenko-6476847.jpg', expertise: 'Information Technology' },
    { id: 7, name: 'Sophia Davis', type: 'Alumni', title: 'VP of HR', company: 'PeopleMatter', image: '/assets/Images/pexels-jopwell-2422292.jpg', expertise: 'Human Resources' },
    { id: 8, name: 'James Wilson', type: 'Alumni', title: 'Chief Data Scientist', company: 'DataMinds', image: '/assets/Images/pexels-christina-morillo-1181715.jpg', expertise: 'Data Science & AI' },
    { id: 9, name: 'Olivia Martinez', type: 'Alumni', title: 'Chief Design Officer', company: 'DesignHub', image: '/assets/Images/pexels-pixabay-162251.jpg', expertise: 'Design & User Experience' },
    { id: 10, name: 'Liam Anderson', type: 'Alumni', title: 'Head of Product', company: 'NextGenTech', image: '/assets/Images/pexels-fauxels-3182832.jpg', expertise: 'Product Management' },
    { id: 11, name: 'Isabella Clark', type: 'Alumni', title: 'VP of Engineering', company: 'BuildRight', image: '/assets/Images/pexels-marcus-aurelius-4065864.jpg', expertise: 'Software Engineering' },
    { id: 12, name: 'Ethan Martinez', type: 'Alumni', title: 'Chief Marketing Officer', company: 'AdVision', image: '/assets/Images/pexels-mentatdgt-2173508.jpg', expertise: 'Digital Marketing' },
    { id: 13, name: 'Mia Taylor', type: 'Alumni', title: 'Chief Strategy Officer', company: 'StrategyX', image: '/assets/Images/pexels-fauxels-3184292.jpg', expertise: 'Corporate Strategy' },
    { id: 14, name: 'Mason Thompson', type: 'Alumni', title: 'Director of Engineering', company: 'TechLink', image: '/assets/Images/pexels-fauxels-3183182.jpg', expertise: 'Full-Stack Development' },
    { id: 15, name: 'Ava Lee', type: 'Alumni', title: 'Director of Operations', company: 'OpsGuru', image: '/assets/Images/pexels-august-de-richelieu-4269656.jpg', expertise: 'Operational Efficiency' },
    { id: 16, name: 'Logan Anderson', type: 'Alumni', title: 'Chief Product Officer', company: 'ProductLab', image: '/assets/Images/pexels-rodnae-productions-5915198.jpg', expertise: 'Product Development' },
    { id: 17, name: 'Amelia Lewis', type: 'Alumni', title: 'Director of Sales', company: 'SalesBoost', image: '/assets/Images/pexels-andrea-piacquadio-3791133.jpg', expertise: 'Sales Strategy' },
    { id: 18, name: 'Lucas Walker', type: 'Alumni', title: 'Head of Analytics', company: 'DataCrunch', image: '/assets/Images/pexels-fauxels-3184318.jpg', expertise: 'Data Analytics' },
    { id: 19, name: 'Charlotte Robinson', type: 'Alumni', title: 'Chief Human Resources Officer', company: 'PeopleFirst', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'HR Management' },
    { id: 20, name: 'Benjamin Harris', type: 'Alumni', title: 'Head of UX', company: 'DesignMind', image: '/assets/Images/pexels-christina-morillo-1181731.jpg', expertise: 'User Experience' },
    { id: 21, name: 'Harper Hall', type: 'Alumni', title: 'Chief Innovation Officer', company: 'InnovateX', image: '/assets/Images/pexels-marcus-aurelius-4064400.jpg', expertise: 'Innovation & Growth' },
    { id: 22, name: 'Elijah Young', type: 'Alumni', title: 'Director of IT', company: 'SecureTech', image: '/assets/Images/pexels-fauxels-3182831.jpg', expertise: 'IT Security' },
    { id: 23, name: 'Evelyn King', type: 'Alumni', title: 'Head of Corporate Communications', company: 'CommsCorp', image: '/assets/Images/pexels-mentatdgt-937481.jpg', expertise: 'Corporate Communications' },
    { id: 24, name: 'Henry Scott', type: 'Alumni', title: 'Chief Legal Officer', company: 'LegalEagle', image: '/assets/Images/pexels-fauxels-3182835.jpg', expertise: 'Corporate Law' },
    { id: 25, name: 'Scarlett Green', type: 'Alumni', title: 'Head of R&D', company: 'ResearchGen', image: '/assets/Images/pexels-andrea-piacquadio-3758107.jpg', expertise: 'Research & Development' },
    { id: 26, name: 'Jack Moore', type: 'Alumni', title: 'VP of Customer Success', company: 'ClientFirst', image: '/assets/Images/pexels-mentatdgt-2173505.jpg', expertise: 'Customer Success' },
    { id: 27, name: 'Lily Adams', type: 'Alumni', title: 'Head of Corporate Strategy', company: 'StratX', image: '/assets/Images/pexels-fauxels-3184326.jpg', expertise: 'Corporate Strategy' },
    { id: 28, name: 'Daniel Parker', type: 'Alumni', title: 'Chief Security Officer', company: 'SecureNow', image: '/assets/Images/pexels-fauxels-3183157.jpg', expertise: 'Cybersecurity' },
    { id: 29, name: 'Grace Mitchell', type: 'Alumni', title: 'Director of Finance', company: 'FinSafe', image: '/assets/Images/pexels-marcus-aurelius-4063783.jpg', expertise: 'Corporate Finance' },
    { id: 30, name: 'Aiden Perez', type: 'Alumni', title: 'Head of Business Development', company: 'BizExpand', image: '/assets/Images/pexels-mentatdgt-937481.jpg', expertise: 'Business Development' },
    { id: 31, name: 'Ella Brooks', type: 'Alumni', title: 'Director of Innovation', company: 'InnoVibe', image: '/assets/Images/pexels-andrea-piacquadio-3781988.jpg', expertise: 'Innovation & Technology' },
    { id: 32, name: 'Sebastian Stewart', type: 'Alumni', title: 'Chief Analytics Officer', company: 'DataGen', image: '/assets/Images/pexels-mentatdgt-2173505.jpg', expertise: 'Data Analytics' },
    { id: 33, name: 'Zoe Sanders', type: 'Alumni', title: 'Head of Supply Chain', company: 'SupplyLink', image: '/assets/Images/pexels-andrea-piacquadio-3758107.jpg', expertise: 'Supply Chain Management' },
    { id: 34, name: 'Leo Murphy', type: 'Alumni', title: 'VP of Strategy', company: 'StratGenius', image: '/assets/Images/pexels-andrea-piacquadio-3781988.jpg', expertise: 'Business Strategy' },
    { id: 35, name: 'Chloe Barnes', type: 'Alumni', title: 'Head of Compliance', company: 'CompliSafe', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'Regulatory Compliance' },
    { id: 36, name: 'Matthew Evans', type: 'Alumni', title: 'Chief Operating Officer', company: 'OpsFirst', image: '/assets/Images/pexels-marcus-aurelius-4063783.jpg', expertise: 'Operations Management' },
    { id: 37, name: 'Madison Reed', type: 'Alumni', title: 'Head of Risk Management', company: 'RiskX', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'Risk Management' },
    { id: 38, name: 'Gabriel Turner', type: 'Alumni', title: 'Director of Business Intelligence', company: 'BizIntel', image: '/assets/Images/pexels-fauxels-3183157.jpg', expertise: 'Business Intelligence' },
    { id: 39, name: 'Avery Bennett', type: 'Alumni', title: 'Head of Legal Affairs', company: 'LegalPro', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'Legal Affairs' },
    { id: 40, name: 'Isaac Phillips', type: 'Alumni', title: 'Director of Cloud Computing', company: 'CloudGen', image: '/assets/Images/pexels-mentatdgt-2173508.jpg', expertise: 'Cloud Computing' },
    { id: 41, name: 'Riley Hughes', type: 'Alumni', title: 'Chief Compliance Officer', company: 'CompliNet', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'Compliance Management' },
    { id: 42, name: 'Luke Richardson', type: 'Alumni', title: 'Director of Marketing', company: 'MarketMinds', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'Marketing Strategy' },
    { id: 43, name: 'Sophie Foster', type: 'Alumni', title: 'Head of Environmental Sustainability', company: 'EcoSolutions', image: '/assets/Images/pexels-marcus-aurelius-4064400.jpg', expertise: 'Sustainability' },
    { id: 44, name: 'Daniel Powell', type: 'Alumni', title: 'Director of Quality Assurance', company: 'QualityFirst', image: '/assets/Images/pexels-andrea-piacquadio-3758107.jpg', expertise: 'Quality Assurance' },
    { id: 45, name: 'Layla Ward', type: 'Alumni', title: 'Head of Logistics', company: 'LogiChain', image: '/assets/Images/pexels-andrea-piacquadio-3781988.jpg', expertise: 'Logistics Management' },
    { id: 46, name: 'Eli Wood', type: 'Alumni', title: 'Chief Compliance Officer', company: 'SafeNet', image: '/assets/Images/pexels-andrea-piacquadio-3758107.jpg', expertise: 'Regulatory Compliance' },
    { id: 47, name: 'Lillian Bennett', type: 'Alumni', title: 'Director of Business Development', company: 'BizGrowth', image: '/assets/Images/pexels-andrea-piacquadio-3758107.jpg', expertise: 'Business Growth' },
    { id: 48, name: 'Jackson Peterson', type: 'Alumni', title: 'Head of Corporate Social Responsibility', company: 'CSRGlobal', image: '/assets/Images/pexels-christina-morillo-1181706.jpg', expertise: 'CSR & Ethics' },
    { id: 49, name: 'Grace Reed', type: 'Alumni', title: 'Director of Finance', company: 'FinExperts', image: '/assets/Images/pexels-mentatdgt-2173508.jpg', expertise: 'Financial Strategy' },
    { id: 50, name: 'Henry Edwards', type: 'Alumni', title: 'Chief Strategy Officer', company: 'StratExperts', image: '/assets/Images/pexels-mentatdgt-937481.jpg', expertise: 'Strategic Planning' }
];

export default alumniProfiles;

